# Generated by Django 5.1 on 2024-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=17)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(null=True)),
                ('course', models.CharField(choices=[('Math', 'Math'), ('Physique', 'Physique'), ('Eps', 'Eps'), ('Anglais', 'Anglais'), ('SVT', 'SVT'), ('Philosophie', 'Philosophie'), ('Français', 'Français')], max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
    ]
