# Generated by Django 5.1 on 2024-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=17)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_de_naissance', models.DateField()),
                ('classe', models.CharField(choices=[('6', '6éme'), ('5', '5éme'), ('4', '4éme'), ('3', '3eme'), ('2', '2nde'), ('1', '1ére'), ('Tle', 'Terminale')], max_length=3)),
                ('telephone', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=7)),
            ],
        ),
    ]
