# Generated by Django 5.1 on 2024-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=17)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField()),
                ('list', models.CharField(choices=[('6', '6éme'), ('5', '5éme'), ('4', '4éme'), ('3', '3eme'), ('2', '2nde'), ('1', '1ére'), ('Tle', 'Terminale')], max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
