# Generated by Django 5.1 on 2024-08-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_delete_eleve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='list',
            new_name='status',
        ),
    ]
