# Generated by Django 5.1 on 2024-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_list_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('6éme', '6éme'), ('5éme', '5éme'), ('4éme', '4éme'), ('3éme', '3eme'), ('2nde', '2nde'), ('1ére', '1ére'), ('Terminale', 'Terminale')], max_length=10),
        ),
    ]
