# Generated by Django 5.1 on 2024-08-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mot_de_passe',
            new_name='password',
        ),
    ]
